frontend:
  zookeeper:
    clusters:
      - datacenter: "dc"
        root: "/run/hermes"
        connectionString: "localhost:2181"
  kafka:
    clusters:
      - datacenter: "dc"
        brokerList: "localhost:9092"
  graphite:
    host: "localhost"
  metrics:
    graphiteReporterEnabled: true
  schema:
    cache:
      refreshAfterWrite: 1m
    repository:
      serverUrl: "http://localhost:8081"