// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schemas/primitives-nullable/NBoolProto.proto

package pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor;

public final class NBoolProto {
  private NBoolProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NullablePrimitivesBoolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NullablePrimitivesBool)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool field = 1;</code>
     * @return Whether the field field is set.
     */
    boolean hasField();
    /**
     * <code>optional bool field = 1;</code>
     * @return The field.
     */
    boolean getField();
  }
  /**
   * Protobuf type {@code pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NullablePrimitivesBool}
   */
  public static final class NullablePrimitivesBool extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NullablePrimitivesBool)
      NullablePrimitivesBoolOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NullablePrimitivesBool.newBuilder() to construct.
    private NullablePrimitivesBool(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NullablePrimitivesBool() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NullablePrimitivesBool();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NullablePrimitivesBool(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              field_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_NullablePrimitivesBool_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_NullablePrimitivesBool_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool.class, pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool.Builder.class);
    }

    private int bitField0_;
    public static final int FIELD_FIELD_NUMBER = 1;
    private boolean field_;
    /**
     * <code>optional bool field = 1;</code>
     * @return Whether the field field is set.
     */
    @java.lang.Override
    public boolean hasField() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bool field = 1;</code>
     * @return The field.
     */
    @java.lang.Override
    public boolean getField() {
      return field_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBool(1, field_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, field_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool)) {
        return super.equals(obj);
      }
      pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool other = (pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool) obj;

      if (hasField() != other.hasField()) return false;
      if (hasField()) {
        if (getField()
            != other.getField()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasField()) {
        hash = (37 * hash) + FIELD_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getField());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NullablePrimitivesBool}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NullablePrimitivesBool)
        pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBoolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_NullablePrimitivesBool_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_NullablePrimitivesBool_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool.class, pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool.Builder.class);
      }

      // Construct using pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        field_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_NullablePrimitivesBool_descriptor;
      }

      @java.lang.Override
      public pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool getDefaultInstanceForType() {
        return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool.getDefaultInstance();
      }

      @java.lang.Override
      public pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool build() {
        pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool buildPartial() {
        pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool result = new pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.field_ = field_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool) {
          return mergeFrom((pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool other) {
        if (other == pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool.getDefaultInstance()) return this;
        if (other.hasField()) {
          setField(other.getField());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean field_ ;
      /**
       * <code>optional bool field = 1;</code>
       * @return Whether the field field is set.
       */
      @java.lang.Override
      public boolean hasField() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bool field = 1;</code>
       * @return The field.
       */
      @java.lang.Override
      public boolean getField() {
        return field_;
      }
      /**
       * <code>optional bool field = 1;</code>
       * @param value The field to set.
       * @return This builder for chaining.
       */
      public Builder setField(boolean value) {
        bitField0_ |= 0x00000001;
        field_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool field = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearField() {
        bitField0_ = (bitField0_ & ~0x00000001);
        field_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NullablePrimitivesBool)
    }

    // @@protoc_insertion_point(class_scope:pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NullablePrimitivesBool)
    private static final pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool();
    }

    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NullablePrimitivesBool>
        PARSER = new com.google.protobuf.AbstractParser<NullablePrimitivesBool>() {
      @java.lang.Override
      public NullablePrimitivesBool parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NullablePrimitivesBool(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NullablePrimitivesBool> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NullablePrimitivesBool> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NBoolProto.NullablePrimitivesBool getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_NullablePrimitivesBool_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_NullablePrimitivesBool_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,schemas/primitives-nullable/NBoolProto" +
      ".proto\022Opl.allegro.tech.hermes.consumers" +
      ".consumer.sender.googlebigquery.avro.des" +
      "criptor\"6\n\026NullablePrimitivesBool\022\022\n\005fie" +
      "ld\030\001 \001(\010H\000\210\001\001B\010\n\006_fieldb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_NullablePrimitivesBool_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_NullablePrimitivesBool_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_NullablePrimitivesBool_descriptor,
        new java.lang.String[] { "Field", "Field", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
