// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schemas/primitives-nullable/NStringProto.proto

package pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor;

public final class NStringProto {
  private NStringProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NullablePrimitivesStringOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NullablePrimitivesString)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string field = 1;</code>
     * @return Whether the field field is set.
     */
    boolean hasField();
    /**
     * <code>optional string field = 1;</code>
     * @return The field.
     */
    java.lang.String getField();
    /**
     * <code>optional string field = 1;</code>
     * @return The bytes for field.
     */
    com.google.protobuf.ByteString
        getFieldBytes();
  }
  /**
   * Protobuf type {@code pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NullablePrimitivesString}
   */
  public static final class NullablePrimitivesString extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NullablePrimitivesString)
      NullablePrimitivesStringOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NullablePrimitivesString.newBuilder() to construct.
    private NullablePrimitivesString(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NullablePrimitivesString() {
      field_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NullablePrimitivesString();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NullablePrimitivesString(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              field_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_NullablePrimitivesString_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_NullablePrimitivesString_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString.class, pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString.Builder.class);
    }

    private int bitField0_;
    public static final int FIELD_FIELD_NUMBER = 1;
    private volatile java.lang.Object field_;
    /**
     * <code>optional string field = 1;</code>
     * @return Whether the field field is set.
     */
    @java.lang.Override
    public boolean hasField() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string field = 1;</code>
     * @return The field.
     */
    @java.lang.Override
    public java.lang.String getField() {
      java.lang.Object ref = field_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        field_ = s;
        return s;
      }
    }
    /**
     * <code>optional string field = 1;</code>
     * @return The bytes for field.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFieldBytes() {
      java.lang.Object ref = field_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        field_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, field_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, field_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString)) {
        return super.equals(obj);
      }
      pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString other = (pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString) obj;

      if (hasField() != other.hasField()) return false;
      if (hasField()) {
        if (!getField()
            .equals(other.getField())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasField()) {
        hash = (37 * hash) + FIELD_FIELD_NUMBER;
        hash = (53 * hash) + getField().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NullablePrimitivesString}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NullablePrimitivesString)
        pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesStringOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_NullablePrimitivesString_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_NullablePrimitivesString_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString.class, pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString.Builder.class);
      }

      // Construct using pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        field_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_NullablePrimitivesString_descriptor;
      }

      @java.lang.Override
      public pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString getDefaultInstanceForType() {
        return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString.getDefaultInstance();
      }

      @java.lang.Override
      public pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString build() {
        pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString buildPartial() {
        pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString result = new pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.field_ = field_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString) {
          return mergeFrom((pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString other) {
        if (other == pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString.getDefaultInstance()) return this;
        if (other.hasField()) {
          bitField0_ |= 0x00000001;
          field_ = other.field_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object field_ = "";
      /**
       * <code>optional string field = 1;</code>
       * @return Whether the field field is set.
       */
      public boolean hasField() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string field = 1;</code>
       * @return The field.
       */
      public java.lang.String getField() {
        java.lang.Object ref = field_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          field_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string field = 1;</code>
       * @return The bytes for field.
       */
      public com.google.protobuf.ByteString
          getFieldBytes() {
        java.lang.Object ref = field_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          field_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string field = 1;</code>
       * @param value The field to set.
       * @return This builder for chaining.
       */
      public Builder setField(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        field_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string field = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearField() {
        bitField0_ = (bitField0_ & ~0x00000001);
        field_ = getDefaultInstance().getField();
        onChanged();
        return this;
      }
      /**
       * <code>optional string field = 1;</code>
       * @param value The bytes for field to set.
       * @return This builder for chaining.
       */
      public Builder setFieldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000001;
        field_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NullablePrimitivesString)
    }

    // @@protoc_insertion_point(class_scope:pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NullablePrimitivesString)
    private static final pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString();
    }

    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NullablePrimitivesString>
        PARSER = new com.google.protobuf.AbstractParser<NullablePrimitivesString>() {
      @java.lang.Override
      public NullablePrimitivesString parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NullablePrimitivesString(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NullablePrimitivesString> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NullablePrimitivesString> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.NStringProto.NullablePrimitivesString getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_NullablePrimitivesString_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_NullablePrimitivesString_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.schemas/primitives-nullable/NStringPro" +
      "to.proto\022Opl.allegro.tech.hermes.consume" +
      "rs.consumer.sender.googlebigquery.avro.d" +
      "escriptor\"8\n\030NullablePrimitivesString\022\022\n" +
      "\005field\030\001 \001(\tH\000\210\001\001B\010\n\006_fieldb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_NullablePrimitivesString_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_NullablePrimitivesString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_NullablePrimitivesString_descriptor,
        new java.lang.String[] { "Field", "Field", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
