// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schemas/primitives-records/RecordBoolProto.proto

package pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor;

public final class RecordBoolProto {
  private RecordBoolProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RecordPrimitivesBoolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesBool)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesBool}
   */
  public static final class RecordPrimitivesBool extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesBool)
      RecordPrimitivesBoolOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RecordPrimitivesBool.newBuilder() to construct.
    private RecordPrimitivesBool(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RecordPrimitivesBool() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RecordPrimitivesBool();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RecordPrimitivesBool(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesBool_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesBool_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.class, pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.Builder.class);
    }

    public interface fieldOrBuilder extends
        // @@protoc_insertion_point(interface_extends:pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesBool.field)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>bool value_field = 1;</code>
       * @return The valueField.
       */
      boolean getValueField();
    }
    /**
     * Protobuf type {@code pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesBool.field}
     */
    public static final class field extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesBool.field)
        fieldOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use field.newBuilder() to construct.
      private field(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private field() {
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new field();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private field(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                valueField_ = input.readBool();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesBool_field_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesBool_field_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field.class, pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field.Builder.class);
      }

      public static final int VALUE_FIELD_FIELD_NUMBER = 1;
      private boolean valueField_;
      /**
       * <code>bool value_field = 1;</code>
       * @return The valueField.
       */
      @java.lang.Override
      public boolean getValueField() {
        return valueField_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (valueField_ != false) {
          output.writeBool(1, valueField_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (valueField_ != false) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(1, valueField_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field)) {
          return super.equals(obj);
        }
        pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field other = (pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field) obj;

        if (getValueField()
            != other.getValueField()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + VALUE_FIELD_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getValueField());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesBool.field}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesBool.field)
          pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.fieldOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesBool_field_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesBool_field_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field.class, pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field.Builder.class);
        }

        // Construct using pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          valueField_ = false;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesBool_field_descriptor;
        }

        @java.lang.Override
        public pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field getDefaultInstanceForType() {
          return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field.getDefaultInstance();
        }

        @java.lang.Override
        public pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field build() {
          pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field buildPartial() {
          pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field result = new pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field(this);
          result.valueField_ = valueField_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field) {
            return mergeFrom((pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field other) {
          if (other == pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field.getDefaultInstance()) return this;
          if (other.getValueField() != false) {
            setValueField(other.getValueField());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private boolean valueField_ ;
        /**
         * <code>bool value_field = 1;</code>
         * @return The valueField.
         */
        @java.lang.Override
        public boolean getValueField() {
          return valueField_;
        }
        /**
         * <code>bool value_field = 1;</code>
         * @param value The valueField to set.
         * @return This builder for chaining.
         */
        public Builder setValueField(boolean value) {
          
          valueField_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>bool value_field = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearValueField() {
          
          valueField_ = false;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesBool.field)
      }

      // @@protoc_insertion_point(class_scope:pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesBool.field)
      private static final pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field();
      }

      public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<field>
          PARSER = new com.google.protobuf.AbstractParser<field>() {
        @java.lang.Override
        public field parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new field(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<field> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<field> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.field getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool)) {
        return super.equals(obj);
      }
      pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool other = (pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesBool}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesBool)
        pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBoolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesBool_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesBool_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.class, pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.Builder.class);
      }

      // Construct using pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesBool_descriptor;
      }

      @java.lang.Override
      public pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool getDefaultInstanceForType() {
        return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.getDefaultInstance();
      }

      @java.lang.Override
      public pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool build() {
        pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool buildPartial() {
        pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool result = new pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool) {
          return mergeFrom((pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool other) {
        if (other == pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesBool)
    }

    // @@protoc_insertion_point(class_scope:pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesBool)
    private static final pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool();
    }

    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RecordPrimitivesBool>
        PARSER = new com.google.protobuf.AbstractParser<RecordPrimitivesBool>() {
      @java.lang.Override
      public RecordPrimitivesBool parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RecordPrimitivesBool(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RecordPrimitivesBool> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RecordPrimitivesBool> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordBoolProto.RecordPrimitivesBool getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesBool_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesBool_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesBool_field_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesBool_field_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0schemas/primitives-records/RecordBoolP" +
      "roto.proto\022Opl.allegro.tech.hermes.consu" +
      "mers.consumer.sender.googlebigquery.avro" +
      ".descriptor\"4\n\024RecordPrimitivesBool\032\034\n\005f" +
      "ield\022\023\n\013value_field\030\001 \001(\010b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesBool_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesBool_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesBool_descriptor,
        new java.lang.String[] { });
    internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesBool_field_descriptor =
      internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesBool_descriptor.getNestedTypes().get(0);
    internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesBool_field_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesBool_field_descriptor,
        new java.lang.String[] { "ValueField", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
