// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schemas/primitives-records/RecordDoubleProto.proto

package pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor;

public final class RecordDoubleProto {
  private RecordDoubleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RecordPrimitivesDoubleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesDouble)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesDouble.Field field = 1;</code>
     * @return Whether the field field is set.
     */
    boolean hasField();
    /**
     * <code>.pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesDouble.Field field = 1;</code>
     * @return The field.
     */
    pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field getField();
    /**
     * <code>.pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesDouble.Field field = 1;</code>
     */
    pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.FieldOrBuilder getFieldOrBuilder();
  }
  /**
   * Protobuf type {@code pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesDouble}
   */
  public static final class RecordPrimitivesDouble extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesDouble)
      RecordPrimitivesDoubleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RecordPrimitivesDouble.newBuilder() to construct.
    private RecordPrimitivesDouble(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RecordPrimitivesDouble() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RecordPrimitivesDouble();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RecordPrimitivesDouble(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field.Builder subBuilder = null;
              if (field_ != null) {
                subBuilder = field_.toBuilder();
              }
              field_ = input.readMessage(pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(field_);
                field_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesDouble_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesDouble_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.class, pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Builder.class);
    }

    public interface FieldOrBuilder extends
        // @@protoc_insertion_point(interface_extends:pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesDouble.Field)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>double value_field = 1;</code>
       * @return The valueField.
       */
      double getValueField();
    }
    /**
     * Protobuf type {@code pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesDouble.Field}
     */
    public static final class Field extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesDouble.Field)
        FieldOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Field.newBuilder() to construct.
      private Field(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Field() {
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Field();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Field(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {

                valueField_ = input.readDouble();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesDouble_Field_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesDouble_Field_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field.class, pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field.Builder.class);
      }

      public static final int VALUE_FIELD_FIELD_NUMBER = 1;
      private double valueField_;
      /**
       * <code>double value_field = 1;</code>
       * @return The valueField.
       */
      @java.lang.Override
      public double getValueField() {
        return valueField_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (java.lang.Double.doubleToRawLongBits(valueField_) != 0) {
          output.writeDouble(1, valueField_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (java.lang.Double.doubleToRawLongBits(valueField_) != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(1, valueField_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field)) {
          return super.equals(obj);
        }
        pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field other = (pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field) obj;

        if (java.lang.Double.doubleToLongBits(getValueField())
            != java.lang.Double.doubleToLongBits(
                other.getValueField())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + VALUE_FIELD_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getValueField()));
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesDouble.Field}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesDouble.Field)
          pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.FieldOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesDouble_Field_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesDouble_Field_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field.class, pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field.Builder.class);
        }

        // Construct using pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          valueField_ = 0D;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesDouble_Field_descriptor;
        }

        @java.lang.Override
        public pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field getDefaultInstanceForType() {
          return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field.getDefaultInstance();
        }

        @java.lang.Override
        public pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field build() {
          pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field buildPartial() {
          pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field result = new pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field(this);
          result.valueField_ = valueField_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field) {
            return mergeFrom((pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field other) {
          if (other == pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field.getDefaultInstance()) return this;
          if (other.getValueField() != 0D) {
            setValueField(other.getValueField());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private double valueField_ ;
        /**
         * <code>double value_field = 1;</code>
         * @return The valueField.
         */
        @java.lang.Override
        public double getValueField() {
          return valueField_;
        }
        /**
         * <code>double value_field = 1;</code>
         * @param value The valueField to set.
         * @return This builder for chaining.
         */
        public Builder setValueField(double value) {
          
          valueField_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>double value_field = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearValueField() {
          
          valueField_ = 0D;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesDouble.Field)
      }

      // @@protoc_insertion_point(class_scope:pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesDouble.Field)
      private static final pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field();
      }

      public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Field>
          PARSER = new com.google.protobuf.AbstractParser<Field>() {
        @java.lang.Override
        public Field parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Field(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Field> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Field> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int FIELD_FIELD_NUMBER = 1;
    private pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field field_;
    /**
     * <code>.pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesDouble.Field field = 1;</code>
     * @return Whether the field field is set.
     */
    @java.lang.Override
    public boolean hasField() {
      return field_ != null;
    }
    /**
     * <code>.pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesDouble.Field field = 1;</code>
     * @return The field.
     */
    @java.lang.Override
    public pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field getField() {
      return field_ == null ? pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field.getDefaultInstance() : field_;
    }
    /**
     * <code>.pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesDouble.Field field = 1;</code>
     */
    @java.lang.Override
    public pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.FieldOrBuilder getFieldOrBuilder() {
      return getField();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (field_ != null) {
        output.writeMessage(1, getField());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (field_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getField());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble)) {
        return super.equals(obj);
      }
      pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble other = (pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble) obj;

      if (hasField() != other.hasField()) return false;
      if (hasField()) {
        if (!getField()
            .equals(other.getField())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasField()) {
        hash = (37 * hash) + FIELD_FIELD_NUMBER;
        hash = (53 * hash) + getField().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesDouble}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesDouble)
        pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDoubleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesDouble_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesDouble_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.class, pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Builder.class);
      }

      // Construct using pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (fieldBuilder_ == null) {
          field_ = null;
        } else {
          field_ = null;
          fieldBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesDouble_descriptor;
      }

      @java.lang.Override
      public pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble getDefaultInstanceForType() {
        return pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.getDefaultInstance();
      }

      @java.lang.Override
      public pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble build() {
        pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble buildPartial() {
        pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble result = new pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble(this);
        if (fieldBuilder_ == null) {
          result.field_ = field_;
        } else {
          result.field_ = fieldBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble) {
          return mergeFrom((pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble other) {
        if (other == pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.getDefaultInstance()) return this;
        if (other.hasField()) {
          mergeField(other.getField());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field field_;
      private com.google.protobuf.SingleFieldBuilderV3<
          pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field, pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field.Builder, pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.FieldOrBuilder> fieldBuilder_;
      /**
       * <code>.pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesDouble.Field field = 1;</code>
       * @return Whether the field field is set.
       */
      public boolean hasField() {
        return fieldBuilder_ != null || field_ != null;
      }
      /**
       * <code>.pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesDouble.Field field = 1;</code>
       * @return The field.
       */
      public pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field getField() {
        if (fieldBuilder_ == null) {
          return field_ == null ? pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field.getDefaultInstance() : field_;
        } else {
          return fieldBuilder_.getMessage();
        }
      }
      /**
       * <code>.pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesDouble.Field field = 1;</code>
       */
      public Builder setField(pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field value) {
        if (fieldBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          field_ = value;
          onChanged();
        } else {
          fieldBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesDouble.Field field = 1;</code>
       */
      public Builder setField(
          pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field.Builder builderForValue) {
        if (fieldBuilder_ == null) {
          field_ = builderForValue.build();
          onChanged();
        } else {
          fieldBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesDouble.Field field = 1;</code>
       */
      public Builder mergeField(pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field value) {
        if (fieldBuilder_ == null) {
          if (field_ != null) {
            field_ =
              pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field.newBuilder(field_).mergeFrom(value).buildPartial();
          } else {
            field_ = value;
          }
          onChanged();
        } else {
          fieldBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesDouble.Field field = 1;</code>
       */
      public Builder clearField() {
        if (fieldBuilder_ == null) {
          field_ = null;
          onChanged();
        } else {
          field_ = null;
          fieldBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesDouble.Field field = 1;</code>
       */
      public pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field.Builder getFieldBuilder() {
        
        onChanged();
        return getFieldFieldBuilder().getBuilder();
      }
      /**
       * <code>.pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesDouble.Field field = 1;</code>
       */
      public pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.FieldOrBuilder getFieldOrBuilder() {
        if (fieldBuilder_ != null) {
          return fieldBuilder_.getMessageOrBuilder();
        } else {
          return field_ == null ?
              pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field.getDefaultInstance() : field_;
        }
      }
      /**
       * <code>.pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesDouble.Field field = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field, pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field.Builder, pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.FieldOrBuilder> 
          getFieldFieldBuilder() {
        if (fieldBuilder_ == null) {
          fieldBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field, pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.Field.Builder, pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble.FieldOrBuilder>(
                  getField(),
                  getParentForChildren(),
                  isClean());
          field_ = null;
        }
        return fieldBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesDouble)
    }

    // @@protoc_insertion_point(class_scope:pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordPrimitivesDouble)
    private static final pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble();
    }

    public static pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RecordPrimitivesDouble>
        PARSER = new com.google.protobuf.AbstractParser<RecordPrimitivesDouble>() {
      @java.lang.Override
      public RecordPrimitivesDouble parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RecordPrimitivesDouble(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RecordPrimitivesDouble> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RecordPrimitivesDouble> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pl.allegro.tech.hermes.consumers.consumer.sender.googlebigquery.avro.descriptor.RecordDoubleProto.RecordPrimitivesDouble getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesDouble_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesDouble_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesDouble_Field_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesDouble_Field_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n2schemas/primitives-records/RecordDoubl" +
      "eProto.proto\022Opl.allegro.tech.hermes.con" +
      "sumers.consumer.sender.googlebigquery.av" +
      "ro.descriptor\"\264\001\n\026RecordPrimitivesDouble" +
      "\022|\n\005field\030\001 \001(\0132m.pl.allegro.tech.hermes" +
      ".consumers.consumer.sender.googlebigquer" +
      "y.avro.descriptor.RecordPrimitivesDouble" +
      ".Field\032\034\n\005Field\022\023\n\013value_field\030\001 \001(\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesDouble_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesDouble_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesDouble_descriptor,
        new java.lang.String[] { "Field", });
    internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesDouble_Field_descriptor =
      internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesDouble_descriptor.getNestedTypes().get(0);
    internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesDouble_Field_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pl_allegro_tech_hermes_consumers_consumer_sender_googlebigquery_avro_descriptor_RecordPrimitivesDouble_Field_descriptor,
        new java.lang.String[] { "ValueField", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
