FROM java:8

MAINTAINER Allegro

RUN apt-get update && apt-get install -y unzip

ENV HERMES_CONSUMERS_OPTS="-Darchaius.configurationSource.additionalUrls=file:///etc/consumers.properties
ADD conf/consumers.properties /etc/consumers.properties
ADD build/hermes-consumers-*.zip hermes-consumers.zip
RUN unzip hermes-consumers.zip -d /opt
RUN mv /opt/hermes-consumers-* /opt/hermes-consumers

CMD /opt/hermes-consumers/bin/hermes-consumers
