version: '3'

services:
  kafka:
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092

  frontend:
    deploy:
      replicas: 0

  consumers:
    deploy:
      replicas: 0

  management:
    deploy:
      replicas: 0