FROM jeanblanchard/java:8

MAINTAINER Allegro

RUN apk update && apk add unzip bash

ENV HERMES_FRONTEND_OPTS="-Darchaius.configurationSource.additionalUrls=file:///etc/hermes/frontend.properties"
ADD latest/frontend/frontend.properties /etc/hermes/frontend.properties
ADD build/hermes-frontend-*.zip /tmp/hermes-frontend.zip
RUN unzip /tmp/hermes-frontend.zip -d /opt \
  && mv /opt/hermes-frontend-* /opt/hermes-frontend \
  && rm /tmp/hermes-frontend.zip

CMD /opt/hermes-frontend/bin/hermes-frontend
