FROM jeanblanchard/java:8

MAINTAINER Allegro

RUN apk update && apk add unzip bash

ENV SPRING_CONFIG_LOCATION="file:///etc/hermes/management.yaml"
ADD latest/management/management.yaml /etc/hermes/management.yaml
ADD build/hermes-management-*.zip /tmp/hermes-management.zip
RUN unzip /tmp/hermes-management.zip -d /opt \
  && mv /opt/hermes-management-* /opt/hermes-management \
  && rm /tmp/hermes-management.zip

CMD /opt/hermes-management/bin/hermes-management
