export const dummyTopicNames = [
  'pl.allegro.public.offer.product.ProductEventV1',
  'pl.allegro.public.offer.product.ProductEventV2',
  'pl.allegro.public.offer.product.ProductEventV3',
  'pl.allegro.public.offer.product.ProductEventV4',
  'pl.allegro.public.offer.OfferEventV1',
  'pl.allegro.public.offer.OfferEventV2',
  'pl.allegro.public.offer.OfferEventV3',
  'pl.allegro.public.order.OrderEventV1',
  'pl.allegro.public.order.OrderEventV2',
  'pl.allegro.public.user.UserCreatedEvent',
  'pl.allegro.public.user.UserChangedEvent',
  'pl.allegro.public.group.DummyEvent',
  'pl.allegro.public.admin.AdminOfferActionEvent',
  'pl.allegro.public.admin.AdminOrderActionEvent',
];
