name: Google java format

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: [ self-hosted, ubuntu-latest ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download and run google java format
        run: |
          ls -la
          curl -sSLO "https://github.com/google/google-java-format/releases/download/v$VERSION/google-java-format-$VERSION-all-deps.jar"
          chmod a+x "google-java-format-$VERSION-all-deps.jar"
          unset JAVA_TOOL_OPTIONS
          ./.github/scripts/check-google-java-format.sh "$VERSION"
        shell: bash
        env:
            VERSION: 1.23.0

