name: "Test report"
on:
  push:
    branches: [ master ]

jobs:
  validation:
    name: "Test report"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Grant execute permission for report downloader
        run: chmod +x ./.github/scripts/download_reports.sh
      - name: Download past reports
        run: ./.github/scripts/download_reports.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Aggregate reports
        run: python ./.github/scripts/reporter.py "test"
